version: 2
updates:
- package-ecosystem: nuget
  directory: /src/PuzzleSolver.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  ignore:
  - dependency-name: "SixLabors.ImageSharp"
    versions: ["3.*"]
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/PuzzleSolver/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  ignore:
  - dependency-name: "SixLabors.ImageSharp"
    versions: ["3.*"]
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
