using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp;

namespace PuzzleSolver
{
    public static class ColorPalettes
    {

        public static List<Rgb24> GetPrimaryColors()
        {
            return new List<Rgb24> {
                Color.Red.ToPixel<Rgb24>(),
                Color.Blue.ToPixel<Rgb24>(),
                Color.Yellow.ToPixel<Rgb24>()};
        }
        
        public static List<Rgb24> GetPrimaryAndSecondaryColors()
        {
            return new List<Rgb24> {
                Color.Red.ToPixel<Rgb24>(),
                Color.Purple.ToPixel<Rgb24>(),
                Color.Blue.ToPixel<Rgb24>(),
                Color.Green.ToPixel<Rgb24>(),
                Color.Yellow.ToPixel<Rgb24>(),
                Color.Orange.ToPixel<Rgb24>(),
                Color.White.ToPixel<Rgb24>(),
                Color.Black.ToPixel<Rgb24>() };
        }

        public static List<Rgb24> GetAllNamedColors()
        {
            return new List<Rgb24> {
                Color.AliceBlue.ToPixel<Rgb24>(),
                Color.AntiqueWhite.ToPixel<Rgb24>(),
                Color.Aqua.ToPixel<Rgb24>(),
                Color.Aquamarine.ToPixel<Rgb24>(),
                Color.Azure.ToPixel<Rgb24>(),
                Color.Beige.ToPixel<Rgb24>(),
                Color.Bisque.ToPixel<Rgb24>(),
                Color.Black.ToPixel<Rgb24>(),
                Color.BlanchedAlmond.ToPixel<Rgb24>(),
                Color.Blue.ToPixel<Rgb24>(),
                Color.BlueViolet.ToPixel<Rgb24>(),
                Color.Brown.ToPixel<Rgb24>(),
                Color.BurlyWood.ToPixel<Rgb24>(),
                Color.CadetBlue.ToPixel<Rgb24>(),
                Color.Chartreuse.ToPixel<Rgb24>(),
                Color.Chocolate.ToPixel<Rgb24>(),
                Color.Coral.ToPixel<Rgb24>(),
                Color.CornflowerBlue.ToPixel<Rgb24>(),
                Color.Cornsilk.ToPixel<Rgb24>(),
                Color.Crimson.ToPixel<Rgb24>(),
                Color.Cyan.ToPixel<Rgb24>(),
                Color.DarkBlue.ToPixel<Rgb24>(),
                Color.DarkCyan.ToPixel<Rgb24>(),
                Color.DarkGoldenrod.ToPixel<Rgb24>(),
                Color.DarkGray.ToPixel<Rgb24>(),
                Color.DarkGreen.ToPixel<Rgb24>(),
                Color.DarkKhaki.ToPixel<Rgb24>(),
                Color.DarkMagenta.ToPixel<Rgb24>(),
                Color.DarkOliveGreen.ToPixel<Rgb24>(),
                Color.DarkOrange.ToPixel<Rgb24>(),
                Color.DarkOrchid.ToPixel<Rgb24>(),
                Color.DarkRed.ToPixel<Rgb24>(),
                Color.DarkSalmon.ToPixel<Rgb24>(),
                Color.DarkSeaGreen.ToPixel<Rgb24>(),
                Color.DarkSlateBlue.ToPixel<Rgb24>(),
                Color.DarkSlateGray.ToPixel<Rgb24>(),
                Color.DarkTurquoise.ToPixel<Rgb24>(),
                Color.DarkViolet.ToPixel<Rgb24>(),
                Color.DeepPink.ToPixel<Rgb24>(),
                Color.DeepSkyBlue.ToPixel<Rgb24>(),
                Color.DimGray.ToPixel<Rgb24>(),
                Color.DodgerBlue.ToPixel<Rgb24>(),
                Color.Firebrick.ToPixel<Rgb24>(),
                Color.FloralWhite.ToPixel<Rgb24>(),
                Color.ForestGreen.ToPixel<Rgb24>(),
                Color.Fuchsia.ToPixel<Rgb24>(),
                Color.Gainsboro.ToPixel<Rgb24>(),
                Color.GhostWhite.ToPixel<Rgb24>(),
                Color.Gold.ToPixel<Rgb24>(),
                Color.Goldenrod.ToPixel<Rgb24>(),
                Color.Gray.ToPixel<Rgb24>(),
                Color.Green.ToPixel<Rgb24>(),
                Color.GreenYellow.ToPixel<Rgb24>(),
                Color.Honeydew.ToPixel<Rgb24>(),
                Color.HotPink.ToPixel<Rgb24>(),
                Color.IndianRed.ToPixel<Rgb24>(),
                Color.Indigo.ToPixel<Rgb24>(),
                Color.Ivory.ToPixel<Rgb24>(),
                Color.Khaki.ToPixel<Rgb24>(),
                Color.Lavender.ToPixel<Rgb24>(),
                Color.LavenderBlush.ToPixel<Rgb24>(),
                Color.LawnGreen.ToPixel<Rgb24>(),
                Color.LemonChiffon.ToPixel<Rgb24>(),
                Color.LightBlue.ToPixel<Rgb24>(),
                Color.LightCoral.ToPixel<Rgb24>(),
                Color.LightCyan.ToPixel<Rgb24>(),
                Color.LightGoldenrodYellow.ToPixel<Rgb24>(),
                Color.LightGray.ToPixel<Rgb24>(),
                Color.LightGreen.ToPixel<Rgb24>(),
                Color.LightPink.ToPixel<Rgb24>(),
                Color.LightSalmon.ToPixel<Rgb24>(),
                Color.LightSeaGreen.ToPixel<Rgb24>(),
                Color.LightSkyBlue.ToPixel<Rgb24>(),
                Color.LightSlateGray.ToPixel<Rgb24>(),
                Color.LightSteelBlue.ToPixel<Rgb24>(),
                Color.LightYellow.ToPixel<Rgb24>(),
                Color.Lime.ToPixel<Rgb24>(),
                Color.LimeGreen.ToPixel<Rgb24>(),
                Color.Linen.ToPixel<Rgb24>(),
                Color.Magenta.ToPixel<Rgb24>(),
                Color.Maroon.ToPixel<Rgb24>(),
                Color.MediumAquamarine.ToPixel<Rgb24>(),
                Color.MediumBlue.ToPixel<Rgb24>(),
                Color.MediumOrchid.ToPixel<Rgb24>(),
                Color.MediumPurple.ToPixel<Rgb24>(),
                Color.MediumSeaGreen.ToPixel<Rgb24>(),
                Color.MediumSlateBlue.ToPixel<Rgb24>(),
                Color.MediumSpringGreen.ToPixel<Rgb24>(),
                Color.MediumTurquoise.ToPixel<Rgb24>(),
                Color.MediumVioletRed.ToPixel<Rgb24>(),
                Color.MidnightBlue.ToPixel<Rgb24>(),
                Color.MintCream.ToPixel<Rgb24>(),
                Color.MistyRose.ToPixel<Rgb24>(),
                Color.Moccasin.ToPixel<Rgb24>(),
                Color.NavajoWhite.ToPixel<Rgb24>(),
                Color.Navy.ToPixel<Rgb24>(),
                Color.OldLace.ToPixel<Rgb24>(),
                Color.Olive.ToPixel<Rgb24>(),
                Color.OliveDrab.ToPixel<Rgb24>(),
                Color.Orange.ToPixel<Rgb24>(),
                Color.OrangeRed.ToPixel<Rgb24>(),
                Color.Orchid.ToPixel<Rgb24>(),
                Color.PaleGoldenrod.ToPixel<Rgb24>(),
                Color.PaleGreen.ToPixel<Rgb24>(),
                Color.PaleTurquoise.ToPixel<Rgb24>(),
                Color.PaleVioletRed.ToPixel<Rgb24>(),
                Color.PapayaWhip.ToPixel<Rgb24>(),
                Color.PeachPuff.ToPixel<Rgb24>(),
                Color.Peru.ToPixel<Rgb24>(),
                Color.Pink.ToPixel<Rgb24>(),
                Color.Plum.ToPixel<Rgb24>(),
                Color.PowderBlue.ToPixel<Rgb24>(),
                Color.Purple.ToPixel<Rgb24>(),
                Color.Red.ToPixel<Rgb24>(),
                Color.RosyBrown.ToPixel<Rgb24>(),
                Color.RoyalBlue.ToPixel<Rgb24>(),
                Color.SaddleBrown.ToPixel<Rgb24>(),
                Color.Salmon.ToPixel<Rgb24>(),
                Color.SandyBrown.ToPixel<Rgb24>(),
                Color.SeaGreen.ToPixel<Rgb24>(),
                Color.SeaShell.ToPixel<Rgb24>(),
                Color.Sienna.ToPixel<Rgb24>(),
                Color.Silver.ToPixel<Rgb24>(),
                Color.SkyBlue.ToPixel<Rgb24>(),
                Color.SlateBlue.ToPixel<Rgb24>(),
                Color.SlateGray.ToPixel<Rgb24>(),
                Color.Snow.ToPixel<Rgb24>(),
                Color.SpringGreen.ToPixel<Rgb24>(),
                Color.SteelBlue.ToPixel<Rgb24>(),
                Color.Tan.ToPixel<Rgb24>(),
                Color.Teal.ToPixel<Rgb24>(),
                Color.Thistle.ToPixel<Rgb24>(),
                Color.Tomato.ToPixel<Rgb24>(),
                Color.Transparent.ToPixel<Rgb24>(),
                Color.Turquoise.ToPixel<Rgb24>(),
                Color.Violet.ToPixel<Rgb24>(),
                Color.Wheat.ToPixel<Rgb24>(),
                Color.White.ToPixel<Rgb24>(),
                Color.WhiteSmoke.ToPixel<Rgb24>(),
                Color.Yellow.ToPixel<Rgb24>(),
                Color.YellowGreen.ToPixel<Rgb24>() };

        }
    }
}
